name: Run default Cypress Tests

on:
  # Run pipeline on every push
  push:
  # Run pipeline on a schedule, every morning at 5am, using cron syntax
  schedule:
    - cron: '0 5 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      # Uses pre-existing github action to initialize pipeline
      - name: Checkout
        uses: actions/checkout@v3

      # Run all tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.3.0
        with:
          browser: chrome
          headed: false
          # config: baseUrl=https://something.com
          # env: 
          #   tags=@testTag,
          #   envVariable=${{ secrets.ENV_VARIABLE_NAME }}

      - name: Save screenshots on fail
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Save videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      # - name: Deploy report to Github Pages
      #   if: always()
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: allure-history

      # - name: Post the link to the report
      #   if: always()
      #   uses: Sibz/github-status-action@v1
      #   with: 
      #       authToken: ${{secrets.GITHUB_TOKEN}}
      #       context: 'Test report'
      #       state: 'success'
      #       sha: ${{ github.event.pull_request.head.sha }}
      #       target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}